title: "Zennで本を執筆する！本の作成マニュアル"
summary: |-
  この本では「Zennで本を作成する手順」を解説しています。
  あなたが詳しい技術やサービスについての知見や、ユニークな経験があるのなら、体系化して本にまとめませんか？細切れの情報は無料で手に入ることも多いですが、体系化された情報は貴重です。堂々と値段をつけて販売してみましょう。

  なお、この本で解説するのはブラウザ上での執筆手順です。Zenn CLIを使った手順は下記のURLをご覧ください。
  https://zenn.dev/zenn/articles/zenn-cli-guide

topics: ["zenn"]
published: true
price: 0 # 有料の場合200〜5000
chapters:
  - about
  - getting-started
  - add-new-chapter
  - change-order
  - set-price
  - free-chapter
  - set-cover
  - viewer
